// Données du site — publié depuis admin.html le 25/08/2026 02:21:29
window.PRODUCTS = [
  {
    "id": 1,
    "slug": "maillot-domicile-psg",
    "name": "Maillot Domicile PSG",
    "team": "PSG",
    "kit": "Domicile",
    "league": "ligue-1",
    "leagueLabel": "Ligue 1",
    "color": "#0055A4",
    "season": "2026/2027",
    "priceOriginal": 17000,
    "price": 12800,
    "discountPct": 25,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique PSG, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-01.jpg",
    "imageSvg": "images/products/maillot-domicile-psg.svg",
    "imageWide": "images/gallery/gallery-01.jpg",
    "stock": 17,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 2,
    "slug": "maillot-domicile-marseille",
    "name": "Maillot Domicile Marseille",
    "team": "Marseille",
    "kit": "Domicile",
    "league": "ligue-1",
    "leagueLabel": "Ligue 1",
    "color": "#0055A4",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 7400,
    "discountPct": 45,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Marseille, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-02.jpg",
    "imageSvg": "images/products/maillot-domicile-marseille.svg",
    "imageWide": "images/gallery/gallery-02.jpg",
    "stock": 11,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 3,
    "slug": "maillot-domicile-lyon",
    "name": "Maillot Domicile Lyon",
    "team": "Lyon",
    "kit": "Domicile",
    "league": "ligue-1",
    "leagueLabel": "Ligue 1",
    "color": "#0055A4",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 10500,
    "discountPct": 30,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Lyon, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-03.jpg",
    "imageSvg": "images/products/maillot-domicile-lyon.svg",
    "imageWide": "images/gallery/gallery-03.jpg",
    "stock": 5,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 4,
    "slug": "maillot-domicile-monaco",
    "name": "Maillot Domicile Monaco",
    "team": "Monaco",
    "kit": "Domicile",
    "league": "ligue-1",
    "leagueLabel": "Ligue 1",
    "color": "#0055A4",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 8200,
    "discountPct": 45,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Monaco, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-04.jpg",
    "imageSvg": "images/products/maillot-domicile-monaco.svg",
    "imageWide": "images/gallery/gallery-04.jpg",
    "stock": 5,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 5,
    "slug": "maillot-domicile-lille",
    "name": "Maillot Domicile Lille",
    "team": "Lille",
    "kit": "Domicile",
    "league": "ligue-1",
    "leagueLabel": "Ligue 1",
    "color": "#0055A4",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 15000,
    "discountPct": 0,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Lille, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-05.jpg",
    "imageSvg": "images/products/maillot-domicile-lille.svg",
    "imageWide": "images/gallery/gallery-05.jpg",
    "stock": 0,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 6,
    "slug": "maillot-domicile-rennes",
    "name": "Maillot Domicile Rennes",
    "team": "Rennes",
    "kit": "Domicile",
    "league": "ligue-1",
    "leagueLabel": "Ligue 1",
    "color": "#0055A4",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 10500,
    "discountPct": 30,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Rennes, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-06.jpg",
    "imageSvg": "images/products/maillot-domicile-rennes.svg",
    "imageWide": "images/gallery/gallery-06.jpg",
    "stock": 10,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 7,
    "slug": "maillot-domicile-nice",
    "name": "Maillot Domicile Nice",
    "team": "Nice",
    "kit": "Domicile",
    "league": "ligue-1",
    "leagueLabel": "Ligue 1",
    "color": "#0055A4",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 8800,
    "discountPct": 35,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Nice, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-07.jpg",
    "imageSvg": "images/products/maillot-domicile-nice.svg",
    "imageWide": "images/gallery/gallery-07.jpg",
    "stock": 4,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 8,
    "slug": "maillot-domicile-lens",
    "name": "Maillot Domicile Lens",
    "team": "Lens",
    "kit": "Domicile",
    "league": "ligue-1",
    "leagueLabel": "Ligue 1",
    "color": "#0055A4",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 8800,
    "discountPct": 41,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Lens, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-08.jpg",
    "imageSvg": "images/products/maillot-domicile-lens.svg",
    "imageWide": "images/gallery/gallery-08.jpg",
    "stock": 1,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 9,
    "slug": "maillot-domicile-strasbourg",
    "name": "Maillot Domicile Strasbourg",
    "team": "Strasbourg",
    "kit": "Domicile",
    "league": "ligue-1",
    "leagueLabel": "Ligue 1",
    "color": "#0055A4",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 7400,
    "discountPct": 45,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Strasbourg, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/maillot-domicile-strasbourg.jpg",
    "imageSvg": "images/products/maillot-domicile-strasbourg.svg",
    "imageWide": "images/photos/maillot-domicile-strasbourg.jpg",
    "stock": 30,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 10,
    "slug": "maillot-domicile-nantes",
    "name": "Maillot Domicile Nantes",
    "team": "Nantes",
    "kit": "Domicile",
    "league": "ligue-1",
    "leagueLabel": "Ligue 1",
    "color": "#0055A4",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 11200,
    "discountPct": 25,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Nantes, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-10.jpg",
    "imageSvg": "images/products/maillot-domicile-nantes.svg",
    "imageWide": "images/gallery/gallery-10.jpg",
    "stock": 15,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 11,
    "slug": "maillot-domicile-toulouse",
    "name": "Maillot Domicile Toulouse",
    "team": "Toulouse",
    "kit": "Domicile",
    "league": "ligue-1",
    "leagueLabel": "Ligue 1",
    "color": "#0055A4",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 15000,
    "discountPct": 0,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Toulouse, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-11.jpg",
    "imageSvg": "images/products/maillot-domicile-toulouse.svg",
    "imageWide": "images/gallery/gallery-11.jpg",
    "stock": 11,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 12,
    "slug": "maillot-domicile-montpellier",
    "name": "Maillot Domicile Montpellier",
    "team": "Montpellier",
    "kit": "Domicile",
    "league": "ligue-1",
    "leagueLabel": "Ligue 1",
    "color": "#0055A4",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 15000,
    "discountPct": 0,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Montpellier, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-12.jpg",
    "imageSvg": "images/products/maillot-domicile-montpellier.svg",
    "imageWide": "images/gallery/gallery-12.jpg",
    "stock": 33,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 13,
    "slug": "maillot-domicile-brest",
    "name": "Maillot Domicile Brest",
    "team": "Brest",
    "kit": "Domicile",
    "league": "ligue-1",
    "leagueLabel": "Ligue 1",
    "color": "#0055A4",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 8200,
    "discountPct": 45,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Brest, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-13.jpg",
    "imageSvg": "images/products/maillot-domicile-brest.svg",
    "imageWide": "images/gallery/gallery-13.jpg",
    "stock": 0,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 14,
    "slug": "maillot-domicile-reims",
    "name": "Maillot Domicile Reims",
    "team": "Reims",
    "kit": "Domicile",
    "league": "ligue-1",
    "leagueLabel": "Ligue 1",
    "color": "#0055A4",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 9400,
    "discountPct": 30,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Reims, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-14.jpg",
    "imageSvg": "images/products/maillot-domicile-reims.svg",
    "imageWide": "images/gallery/gallery-14.jpg",
    "stock": 16,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 15,
    "slug": "maillot-domicile-le-havre",
    "name": "Maillot Domicile Le Havre",
    "team": "Le Havre",
    "kit": "Domicile",
    "league": "ligue-1",
    "leagueLabel": "Ligue 1",
    "color": "#0055A4",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 10500,
    "discountPct": 30,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Le Havre, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-15.jpg",
    "imageSvg": "images/products/maillot-domicile-le-havre.svg",
    "imageWide": "images/gallery/gallery-15.jpg",
    "stock": 17,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 16,
    "slug": "maillot-domicile-angers",
    "name": "Maillot Domicile Angers",
    "team": "Angers",
    "kit": "Domicile",
    "league": "ligue-1",
    "leagueLabel": "Ligue 1",
    "color": "#0055A4",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 11200,
    "discountPct": 25,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Angers, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-16.jpg",
    "imageSvg": "images/products/maillot-domicile-angers.svg",
    "imageWide": "images/gallery/gallery-16.jpg",
    "stock": 27,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 17,
    "slug": "maillot-domicile-auxerre",
    "name": "Maillot Domicile Auxerre",
    "team": "Auxerre",
    "kit": "Domicile",
    "league": "ligue-1",
    "leagueLabel": "Ligue 1",
    "color": "#0055A4",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 13500,
    "discountPct": 0,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Auxerre, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-01.jpg",
    "imageSvg": "images/products/maillot-domicile-auxerre.svg",
    "imageWide": "images/gallery/gallery-01.jpg",
    "stock": 19,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 18,
    "slug": "maillot-domicile-metz",
    "name": "Maillot Domicile Metz",
    "team": "Metz",
    "kit": "Domicile",
    "league": "ligue-1",
    "leagueLabel": "Ligue 1",
    "color": "#0055A4",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 7400,
    "discountPct": 45,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Metz, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-02.jpg",
    "imageSvg": "images/products/maillot-domicile-metz.svg",
    "imageWide": "images/gallery/gallery-02.jpg",
    "stock": 5,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 19,
    "slug": "maillot-domicile-saint-etienne",
    "name": "Maillot Domicile Saint-Étienne",
    "team": "Saint-Étienne",
    "kit": "Domicile",
    "league": "ligue-1",
    "leagueLabel": "Ligue 1",
    "color": "#0055A4",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 8800,
    "discountPct": 35,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Saint-Étienne, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-03.jpg",
    "imageSvg": "images/products/maillot-domicile-saint-etienne.svg",
    "imageWide": "images/gallery/gallery-03.jpg",
    "stock": 31,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 20,
    "slug": "maillot-domicile-manchester-city",
    "name": "Maillot Domicile Manchester City",
    "team": "Manchester City",
    "kit": "Domicile",
    "league": "premier-league",
    "leagueLabel": "Premier League",
    "color": "#3D195B",
    "season": "2026/2027",
    "priceOriginal": 17000,
    "price": 11000,
    "discountPct": 35,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Manchester City, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-04.jpg",
    "imageSvg": "images/products/maillot-domicile-manchester-city.svg",
    "imageWide": "images/gallery/gallery-04.jpg",
    "stock": 1,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 21,
    "slug": "maillot-domicile-manchester-united",
    "name": "Maillot Domicile Manchester United",
    "team": "Manchester United",
    "kit": "Domicile",
    "league": "premier-league",
    "leagueLabel": "Premier League",
    "color": "#3D195B",
    "season": "2026/2027",
    "priceOriginal": 17000,
    "price": 12800,
    "discountPct": 25,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Manchester United, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-05.jpg",
    "imageSvg": "images/products/maillot-domicile-manchester-united.svg",
    "imageWide": "images/gallery/gallery-05.jpg",
    "stock": 21,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 22,
    "slug": "maillot-domicile-liverpool",
    "name": "Maillot Domicile Liverpool",
    "team": "Liverpool",
    "kit": "Domicile",
    "league": "premier-league",
    "leagueLabel": "Premier League",
    "color": "#3D195B",
    "season": "2026/2027",
    "priceOriginal": 17000,
    "price": 11900,
    "discountPct": 30,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Liverpool, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-06.jpg",
    "imageSvg": "images/products/maillot-domicile-liverpool.svg",
    "imageWide": "images/gallery/gallery-06.jpg",
    "stock": 35,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 23,
    "slug": "maillot-domicile-arsenal",
    "name": "Maillot Domicile Arsenal",
    "team": "Arsenal",
    "kit": "Domicile",
    "league": "premier-league",
    "leagueLabel": "Premier League",
    "color": "#3D195B",
    "season": "2026/2027",
    "priceOriginal": 17000,
    "price": 10500,
    "discountPct": 38,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Arsenal, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-07.jpg",
    "imageSvg": "images/products/maillot-domicile-arsenal.svg",
    "imageWide": "images/gallery/gallery-07.jpg",
    "stock": 37,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 24,
    "slug": "maillot-domicile-chelsea",
    "name": "Maillot Domicile Chelsea",
    "team": "Chelsea",
    "kit": "Domicile",
    "league": "premier-league",
    "leagueLabel": "Premier League",
    "color": "#3D195B",
    "season": "2026/2027",
    "priceOriginal": 17000,
    "price": 10000,
    "discountPct": 41,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Chelsea, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-08.jpg",
    "imageSvg": "images/products/maillot-domicile-chelsea.svg",
    "imageWide": "images/gallery/gallery-08.jpg",
    "stock": 37,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 25,
    "slug": "maillot-domicile-tottenham",
    "name": "Maillot Domicile Tottenham",
    "team": "Tottenham",
    "kit": "Domicile",
    "league": "premier-league",
    "leagueLabel": "Premier League",
    "color": "#3D195B",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 8800,
    "discountPct": 41,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Tottenham, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-09.jpg",
    "imageSvg": "images/products/maillot-domicile-tottenham.svg",
    "imageWide": "images/gallery/gallery-09.jpg",
    "stock": 23,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 26,
    "slug": "maillot-domicile-newcastle",
    "name": "Maillot Domicile Newcastle",
    "team": "Newcastle",
    "kit": "Domicile",
    "league": "premier-league",
    "leagueLabel": "Premier League",
    "color": "#3D195B",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 9400,
    "discountPct": 30,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Newcastle, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-10.jpg",
    "imageSvg": "images/products/maillot-domicile-newcastle.svg",
    "imageWide": "images/gallery/gallery-10.jpg",
    "stock": 23,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 27,
    "slug": "maillot-domicile-aston-villa",
    "name": "Maillot Domicile Aston Villa",
    "team": "Aston Villa",
    "kit": "Domicile",
    "league": "premier-league",
    "leagueLabel": "Premier League",
    "color": "#3D195B",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 8800,
    "discountPct": 41,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Aston Villa, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-11.jpg",
    "imageSvg": "images/products/maillot-domicile-aston-villa.svg",
    "imageWide": "images/gallery/gallery-11.jpg",
    "stock": 3,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 28,
    "slug": "maillot-domicile-west-ham",
    "name": "Maillot Domicile West Ham",
    "team": "West Ham",
    "kit": "Domicile",
    "league": "premier-league",
    "leagueLabel": "Premier League",
    "color": "#3D195B",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 7400,
    "discountPct": 45,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique West Ham, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-12.jpg",
    "imageSvg": "images/products/maillot-domicile-west-ham.svg",
    "imageWide": "images/gallery/gallery-12.jpg",
    "stock": 29,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 29,
    "slug": "maillot-domicile-brighton",
    "name": "Maillot Domicile Brighton",
    "team": "Brighton",
    "kit": "Domicile",
    "league": "premier-league",
    "leagueLabel": "Premier League",
    "color": "#3D195B",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 8000,
    "discountPct": 41,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Brighton, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-13.jpg",
    "imageSvg": "images/products/maillot-domicile-brighton.svg",
    "imageWide": "images/gallery/gallery-13.jpg",
    "stock": 26,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 30,
    "slug": "maillot-domicile-everton",
    "name": "Maillot Domicile Everton",
    "team": "Everton",
    "kit": "Domicile",
    "league": "premier-league",
    "leagueLabel": "Premier League",
    "color": "#3D195B",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 9800,
    "discountPct": 35,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Everton, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-14.jpg",
    "imageSvg": "images/products/maillot-domicile-everton.svg",
    "imageWide": "images/gallery/gallery-14.jpg",
    "stock": 12,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 31,
    "slug": "maillot-domicile-wolves",
    "name": "Maillot Domicile Wolves",
    "team": "Wolves",
    "kit": "Domicile",
    "league": "premier-league",
    "leagueLabel": "Premier League",
    "color": "#3D195B",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 8000,
    "discountPct": 41,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Wolves, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-15.jpg",
    "imageSvg": "images/products/maillot-domicile-wolves.svg",
    "imageWide": "images/gallery/gallery-15.jpg",
    "stock": 4,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 32,
    "slug": "maillot-domicile-crystal-palace",
    "name": "Maillot Domicile Crystal Palace",
    "team": "Crystal Palace",
    "kit": "Domicile",
    "league": "premier-league",
    "leagueLabel": "Premier League",
    "color": "#3D195B",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 8800,
    "discountPct": 41,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Crystal Palace, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-16.jpg",
    "imageSvg": "images/products/maillot-domicile-crystal-palace.svg",
    "imageWide": "images/gallery/gallery-16.jpg",
    "stock": 3,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 33,
    "slug": "maillot-domicile-fulham",
    "name": "Maillot Domicile Fulham",
    "team": "Fulham",
    "kit": "Domicile",
    "league": "premier-league",
    "leagueLabel": "Premier League",
    "color": "#3D195B",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 9800,
    "discountPct": 35,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Fulham, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-01.jpg",
    "imageSvg": "images/products/maillot-domicile-fulham.svg",
    "imageWide": "images/gallery/gallery-01.jpg",
    "stock": 4,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 34,
    "slug": "maillot-domicile-brentford",
    "name": "Maillot Domicile Brentford",
    "team": "Brentford",
    "kit": "Domicile",
    "league": "premier-league",
    "leagueLabel": "Premier League",
    "color": "#3D195B",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 15000,
    "discountPct": 0,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Brentford, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-02.jpg",
    "imageSvg": "images/products/maillot-domicile-brentford.svg",
    "imageWide": "images/gallery/gallery-02.jpg",
    "stock": 12,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 35,
    "slug": "maillot-domicile-nottingham-forest",
    "name": "Maillot Domicile Nottingham Forest",
    "team": "Nottingham Forest",
    "kit": "Domicile",
    "league": "premier-league",
    "leagueLabel": "Premier League",
    "color": "#3D195B",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 8200,
    "discountPct": 45,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Nottingham Forest, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-03.jpg",
    "imageSvg": "images/products/maillot-domicile-nottingham-forest.svg",
    "imageWide": "images/gallery/gallery-03.jpg",
    "stock": 28,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 36,
    "slug": "maillot-domicile-bournemouth",
    "name": "Maillot Domicile Bournemouth",
    "team": "Bournemouth",
    "kit": "Domicile",
    "league": "premier-league",
    "leagueLabel": "Premier League",
    "color": "#3D195B",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 10500,
    "discountPct": 30,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Bournemouth, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-04.jpg",
    "imageSvg": "images/products/maillot-domicile-bournemouth.svg",
    "imageWide": "images/gallery/gallery-04.jpg",
    "stock": 30,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 37,
    "slug": "maillot-domicile-leicester",
    "name": "Maillot Domicile Leicester",
    "team": "Leicester",
    "kit": "Domicile",
    "league": "premier-league",
    "leagueLabel": "Premier League",
    "color": "#3D195B",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 11200,
    "discountPct": 25,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Leicester, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-05.jpg",
    "imageSvg": "images/products/maillot-domicile-leicester.svg",
    "imageWide": "images/gallery/gallery-05.jpg",
    "stock": 37,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 38,
    "slug": "maillot-domicile-southampton",
    "name": "Maillot Domicile Southampton",
    "team": "Southampton",
    "kit": "Domicile",
    "league": "premier-league",
    "leagueLabel": "Premier League",
    "color": "#3D195B",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 13500,
    "discountPct": 0,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Southampton, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-06.jpg",
    "imageSvg": "images/products/maillot-domicile-southampton.svg",
    "imageWide": "images/gallery/gallery-06.jpg",
    "stock": 1,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 39,
    "slug": "maillot-domicile-real-madrid",
    "name": "Maillot Domicile Real Madrid",
    "team": "Real Madrid",
    "kit": "Domicile",
    "league": "liga",
    "leagueLabel": "Liga",
    "color": "#EE8707",
    "season": "2026/2027",
    "priceOriginal": 17000,
    "price": 9400,
    "discountPct": 45,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Real Madrid, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-07.jpg",
    "imageSvg": "images/products/maillot-domicile-real-madrid.svg",
    "imageWide": "images/gallery/gallery-07.jpg",
    "stock": 38,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 40,
    "slug": "maillot-domicile-barcelone",
    "name": "Maillot Domicile Barcelone",
    "team": "Barcelone",
    "kit": "Domicile",
    "league": "liga",
    "leagueLabel": "Liga",
    "color": "#EE8707",
    "season": "2026/2027",
    "priceOriginal": 17000,
    "price": 10000,
    "discountPct": 41,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Barcelone, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-08.jpg",
    "imageSvg": "images/products/maillot-domicile-barcelone.svg",
    "imageWide": "images/gallery/gallery-08.jpg",
    "stock": 12,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 41,
    "slug": "maillot-domicile-atletico-madrid",
    "name": "Maillot Domicile Atlético Madrid",
    "team": "Atlético Madrid",
    "kit": "Domicile",
    "league": "liga",
    "leagueLabel": "Liga",
    "color": "#EE8707",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 11200,
    "discountPct": 25,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Atlético Madrid, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-09.jpg",
    "imageSvg": "images/products/maillot-domicile-atletico-madrid.svg",
    "imageWide": "images/gallery/gallery-09.jpg",
    "stock": 3,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 42,
    "slug": "maillot-domicile-real-sociedad",
    "name": "Maillot Domicile Real Sociedad",
    "team": "Real Sociedad",
    "kit": "Domicile",
    "league": "liga",
    "leagueLabel": "Liga",
    "color": "#EE8707",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 8200,
    "discountPct": 45,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Real Sociedad, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-10.jpg",
    "imageSvg": "images/products/maillot-domicile-real-sociedad.svg",
    "imageWide": "images/gallery/gallery-10.jpg",
    "stock": 36,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 43,
    "slug": "maillot-domicile-seville",
    "name": "Maillot Domicile Séville",
    "team": "Séville",
    "kit": "Domicile",
    "league": "liga",
    "leagueLabel": "Liga",
    "color": "#EE8707",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 8200,
    "discountPct": 45,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Séville, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-11.jpg",
    "imageSvg": "images/products/maillot-domicile-seville.svg",
    "imageWide": "images/gallery/gallery-11.jpg",
    "stock": 32,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 44,
    "slug": "maillot-domicile-real-betis",
    "name": "Maillot Domicile Real Betis",
    "team": "Real Betis",
    "kit": "Domicile",
    "league": "liga",
    "leagueLabel": "Liga",
    "color": "#EE8707",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 8400,
    "discountPct": 38,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Real Betis, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-12.jpg",
    "imageSvg": "images/products/maillot-domicile-real-betis.svg",
    "imageWide": "images/gallery/gallery-12.jpg",
    "stock": 30,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 45,
    "slug": "maillot-domicile-athletic-bilbao",
    "name": "Maillot Domicile Athletic Bilbao",
    "team": "Athletic Bilbao",
    "kit": "Domicile",
    "league": "liga",
    "leagueLabel": "Liga",
    "color": "#EE8707",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 15000,
    "discountPct": 0,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Athletic Bilbao, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-13.jpg",
    "imageSvg": "images/products/maillot-domicile-athletic-bilbao.svg",
    "imageWide": "images/gallery/gallery-13.jpg",
    "stock": 0,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 46,
    "slug": "maillot-domicile-valence",
    "name": "Maillot Domicile Valence",
    "team": "Valence",
    "kit": "Domicile",
    "league": "liga",
    "leagueLabel": "Liga",
    "color": "#EE8707",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 8200,
    "discountPct": 45,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Valence, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-14.jpg",
    "imageSvg": "images/products/maillot-domicile-valence.svg",
    "imageWide": "images/gallery/gallery-14.jpg",
    "stock": 18,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 47,
    "slug": "maillot-domicile-juventus",
    "name": "Maillot Domicile Juventus",
    "team": "Juventus",
    "kit": "Domicile",
    "league": "serie-a",
    "leagueLabel": "Serie A",
    "color": "#008C45",
    "season": "2026/2027",
    "priceOriginal": 17000,
    "price": 17000,
    "discountPct": 0,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Juventus, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-15.jpg",
    "imageSvg": "images/products/maillot-domicile-juventus.svg",
    "imageWide": "images/gallery/gallery-15.jpg",
    "stock": 39,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 48,
    "slug": "maillot-domicile-inter-milan",
    "name": "Maillot Domicile Inter Milan",
    "team": "Inter Milan",
    "kit": "Domicile",
    "league": "serie-a",
    "leagueLabel": "Serie A",
    "color": "#008C45",
    "season": "2026/2027",
    "priceOriginal": 17000,
    "price": 10500,
    "discountPct": 38,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Inter Milan, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-16.jpg",
    "imageSvg": "images/products/maillot-domicile-inter-milan.svg",
    "imageWide": "images/gallery/gallery-16.jpg",
    "stock": 0,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 49,
    "slug": "maillot-domicile-ac-milan",
    "name": "Maillot Domicile AC Milan",
    "team": "AC Milan",
    "kit": "Domicile",
    "league": "serie-a",
    "leagueLabel": "Serie A",
    "color": "#008C45",
    "season": "2026/2027",
    "priceOriginal": 17000,
    "price": 17000,
    "discountPct": 0,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique AC Milan, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-01.jpg",
    "imageSvg": "images/products/maillot-domicile-ac-milan.svg",
    "imageWide": "images/gallery/gallery-01.jpg",
    "stock": 16,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 50,
    "slug": "maillot-domicile-naples",
    "name": "Maillot Domicile Naples",
    "team": "Naples",
    "kit": "Domicile",
    "league": "serie-a",
    "leagueLabel": "Serie A",
    "color": "#008C45",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 13500,
    "discountPct": 0,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Naples, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-02.jpg",
    "imageSvg": "images/products/maillot-domicile-naples.svg",
    "imageWide": "images/gallery/gallery-02.jpg",
    "stock": 33,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 51,
    "slug": "maillot-domicile-as-roma",
    "name": "Maillot Domicile AS Roma",
    "team": "AS Roma",
    "kit": "Domicile",
    "league": "serie-a",
    "leagueLabel": "Serie A",
    "color": "#008C45",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 8800,
    "discountPct": 41,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique AS Roma, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-03.jpg",
    "imageSvg": "images/products/maillot-domicile-as-roma.svg",
    "imageWide": "images/gallery/gallery-03.jpg",
    "stock": 39,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 52,
    "slug": "maillot-domicile-fiorentina",
    "name": "Maillot Domicile Fiorentina",
    "team": "Fiorentina",
    "kit": "Domicile",
    "league": "serie-a",
    "leagueLabel": "Serie A",
    "color": "#008C45",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 10100,
    "discountPct": 25,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Fiorentina, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-04.jpg",
    "imageSvg": "images/products/maillot-domicile-fiorentina.svg",
    "imageWide": "images/gallery/gallery-04.jpg",
    "stock": 4,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 53,
    "slug": "maillot-domicile-atalanta",
    "name": "Maillot Domicile Atalanta",
    "team": "Atalanta",
    "kit": "Domicile",
    "league": "serie-a",
    "leagueLabel": "Serie A",
    "color": "#008C45",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 8800,
    "discountPct": 41,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Atalanta, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-05.jpg",
    "imageSvg": "images/products/maillot-domicile-atalanta.svg",
    "imageWide": "images/gallery/gallery-05.jpg",
    "stock": 25,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 54,
    "slug": "maillot-domicile-lazio",
    "name": "Maillot Domicile Lazio",
    "team": "Lazio",
    "kit": "Domicile",
    "league": "serie-a",
    "leagueLabel": "Serie A",
    "color": "#008C45",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 8800,
    "discountPct": 41,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Lazio, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-06.jpg",
    "imageSvg": "images/products/maillot-domicile-lazio.svg",
    "imageWide": "images/gallery/gallery-06.jpg",
    "stock": 35,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 55,
    "slug": "maillot-domicile-bayern-munich",
    "name": "Maillot Domicile Bayern Munich",
    "team": "Bayern Munich",
    "kit": "Domicile",
    "league": "bundesliga",
    "leagueLabel": "Bundesliga",
    "color": "#D3010C",
    "season": "2026/2027",
    "priceOriginal": 17000,
    "price": 9400,
    "discountPct": 45,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Bayern Munich, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-07.jpg",
    "imageSvg": "images/products/maillot-domicile-bayern-munich.svg",
    "imageWide": "images/gallery/gallery-07.jpg",
    "stock": 25,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 56,
    "slug": "maillot-domicile-borussia-dortmund",
    "name": "Maillot Domicile Borussia Dortmund",
    "team": "Borussia Dortmund",
    "kit": "Domicile",
    "league": "bundesliga",
    "leagueLabel": "Bundesliga",
    "color": "#D3010C",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 8800,
    "discountPct": 41,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Borussia Dortmund, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-08.jpg",
    "imageSvg": "images/products/maillot-domicile-borussia-dortmund.svg",
    "imageWide": "images/gallery/gallery-08.jpg",
    "stock": 30,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 57,
    "slug": "maillot-domicile-rb-leipzig",
    "name": "Maillot Domicile RB Leipzig",
    "team": "RB Leipzig",
    "kit": "Domicile",
    "league": "bundesliga",
    "leagueLabel": "Bundesliga",
    "color": "#D3010C",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 8800,
    "discountPct": 41,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique RB Leipzig, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-09.jpg",
    "imageSvg": "images/products/maillot-domicile-rb-leipzig.svg",
    "imageWide": "images/gallery/gallery-09.jpg",
    "stock": 32,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 58,
    "slug": "maillot-domicile-bayer-leverkusen",
    "name": "Maillot Domicile Bayer Leverkusen",
    "team": "Bayer Leverkusen",
    "kit": "Domicile",
    "league": "bundesliga",
    "leagueLabel": "Bundesliga",
    "color": "#D3010C",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 9800,
    "discountPct": 35,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Bayer Leverkusen, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-10.jpg",
    "imageSvg": "images/products/maillot-domicile-bayer-leverkusen.svg",
    "imageWide": "images/gallery/gallery-10.jpg",
    "stock": 17,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 59,
    "slug": "maillot-domicile-eintracht-francfort",
    "name": "Maillot Domicile Eintracht Francfort",
    "team": "Eintracht Francfort",
    "kit": "Domicile",
    "league": "bundesliga",
    "leagueLabel": "Bundesliga",
    "color": "#D3010C",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 10100,
    "discountPct": 25,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Eintracht Francfort, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-11.jpg",
    "imageSvg": "images/products/maillot-domicile-eintracht-francfort.svg",
    "imageWide": "images/gallery/gallery-11.jpg",
    "stock": 2,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 60,
    "slug": "maillot-domicile-borussia-m-nchengladbach",
    "name": "Maillot Domicile Borussia Mönchengladbach",
    "team": "Borussia Mönchengladbach",
    "kit": "Domicile",
    "league": "bundesliga",
    "leagueLabel": "Bundesliga",
    "color": "#D3010C",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 8800,
    "discountPct": 41,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Borussia Mönchengladbach, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-12.jpg",
    "imageSvg": "images/products/maillot-domicile-borussia-m-nchengladbach.svg",
    "imageWide": "images/gallery/gallery-12.jpg",
    "stock": 22,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 61,
    "slug": "maillot-domicile-cameroun",
    "name": "Maillot Domicile Cameroun",
    "team": "Cameroun",
    "kit": "Domicile",
    "league": "equipes-nationales",
    "leagueLabel": "Équipes Nationales",
    "color": "#1C7C3F",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 15000,
    "discountPct": 0,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Cameroun, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-13.jpg",
    "imageSvg": "images/products/maillot-domicile-cameroun.svg",
    "imageWide": "images/gallery/gallery-13.jpg",
    "stock": 0,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 62,
    "slug": "maillot-domicile-france",
    "name": "Maillot Domicile France",
    "team": "France",
    "kit": "Domicile",
    "league": "equipes-nationales",
    "leagueLabel": "Équipes Nationales",
    "color": "#1C7C3F",
    "season": "2026/2027",
    "priceOriginal": 17000,
    "price": 10000,
    "discountPct": 41,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique France, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-14.jpg",
    "imageSvg": "images/products/maillot-domicile-france.svg",
    "imageWide": "images/gallery/gallery-14.jpg",
    "stock": 19,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 63,
    "slug": "maillot-domicile-bresil",
    "name": "Maillot Domicile Brésil",
    "team": "Brésil",
    "kit": "Domicile",
    "league": "equipes-nationales",
    "leagueLabel": "Équipes Nationales",
    "color": "#1C7C3F",
    "season": "2026/2027",
    "priceOriginal": 17000,
    "price": 17000,
    "discountPct": 0,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Brésil, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-15.jpg",
    "imageSvg": "images/products/maillot-domicile-bresil.svg",
    "imageWide": "images/gallery/gallery-15.jpg",
    "stock": 8,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 64,
    "slug": "maillot-domicile-argentine",
    "name": "Maillot Domicile Argentine",
    "team": "Argentine",
    "kit": "Domicile",
    "league": "equipes-nationales",
    "leagueLabel": "Équipes Nationales",
    "color": "#1C7C3F",
    "season": "2026/2027",
    "priceOriginal": 17000,
    "price": 17000,
    "discountPct": 0,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Argentine, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-16.jpg",
    "imageSvg": "images/products/maillot-domicile-argentine.svg",
    "imageWide": "images/gallery/gallery-16.jpg",
    "stock": 5,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 65,
    "slug": "maillot-domicile-portugal",
    "name": "Maillot Domicile Portugal",
    "team": "Portugal",
    "kit": "Domicile",
    "league": "equipes-nationales",
    "leagueLabel": "Équipes Nationales",
    "color": "#1C7C3F",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 11200,
    "discountPct": 25,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Portugal, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-01.jpg",
    "imageSvg": "images/products/maillot-domicile-portugal.svg",
    "imageWide": "images/gallery/gallery-01.jpg",
    "stock": 28,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 66,
    "slug": "maillot-domicile-espagne",
    "name": "Maillot Domicile Espagne",
    "team": "Espagne",
    "kit": "Domicile",
    "league": "equipes-nationales",
    "leagueLabel": "Équipes Nationales",
    "color": "#1C7C3F",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 9400,
    "discountPct": 30,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Espagne, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-02.jpg",
    "imageSvg": "images/products/maillot-domicile-espagne.svg",
    "imageWide": "images/gallery/gallery-02.jpg",
    "stock": 40,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 67,
    "slug": "maillot-domicile-allemagne",
    "name": "Maillot Domicile Allemagne",
    "team": "Allemagne",
    "kit": "Domicile",
    "league": "equipes-nationales",
    "leagueLabel": "Équipes Nationales",
    "color": "#1C7C3F",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 9300,
    "discountPct": 38,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Allemagne, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-03.jpg",
    "imageSvg": "images/products/maillot-domicile-allemagne.svg",
    "imageWide": "images/gallery/gallery-03.jpg",
    "stock": 11,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 68,
    "slug": "maillot-domicile-angleterre",
    "name": "Maillot Domicile Angleterre",
    "team": "Angleterre",
    "kit": "Domicile",
    "league": "equipes-nationales",
    "leagueLabel": "Équipes Nationales",
    "color": "#1C7C3F",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 8800,
    "discountPct": 35,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Angleterre, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-04.jpg",
    "imageSvg": "images/products/maillot-domicile-angleterre.svg",
    "imageWide": "images/gallery/gallery-04.jpg",
    "stock": 33,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 69,
    "slug": "maillot-domicile-belgique",
    "name": "Maillot Domicile Belgique",
    "team": "Belgique",
    "kit": "Domicile",
    "league": "equipes-nationales",
    "leagueLabel": "Équipes Nationales",
    "color": "#1C7C3F",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 13500,
    "discountPct": 0,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Belgique, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-05.jpg",
    "imageSvg": "images/products/maillot-domicile-belgique.svg",
    "imageWide": "images/gallery/gallery-05.jpg",
    "stock": 33,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 70,
    "slug": "maillot-domicile-senegal",
    "name": "Maillot Domicile Sénégal",
    "team": "Sénégal",
    "kit": "Domicile",
    "league": "equipes-nationales",
    "leagueLabel": "Équipes Nationales",
    "color": "#1C7C3F",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 11200,
    "discountPct": 25,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Sénégal, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-06.jpg",
    "imageSvg": "images/products/maillot-domicile-senegal.svg",
    "imageWide": "images/gallery/gallery-06.jpg",
    "stock": 4,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 71,
    "slug": "maillot-domicile-cote-d-ivoire",
    "name": "Maillot Domicile Côte d'Ivoire",
    "team": "Côte d'Ivoire",
    "kit": "Domicile",
    "league": "equipes-nationales",
    "leagueLabel": "Équipes Nationales",
    "color": "#1C7C3F",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 9800,
    "discountPct": 35,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Côte d'Ivoire, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-07.jpg",
    "imageSvg": "images/products/maillot-domicile-cote-d-ivoire.svg",
    "imageWide": "images/gallery/gallery-07.jpg",
    "stock": 1,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 72,
    "slug": "maillot-domicile-nigeria",
    "name": "Maillot Domicile Nigeria",
    "team": "Nigeria",
    "kit": "Domicile",
    "league": "equipes-nationales",
    "leagueLabel": "Équipes Nationales",
    "color": "#1C7C3F",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 10100,
    "discountPct": 25,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Nigeria, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-08.jpg",
    "imageSvg": "images/products/maillot-domicile-nigeria.svg",
    "imageWide": "images/gallery/gallery-08.jpg",
    "stock": 36,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 73,
    "slug": "maillot-domicile-maroc",
    "name": "Maillot Domicile Maroc",
    "team": "Maroc",
    "kit": "Domicile",
    "league": "equipes-nationales",
    "leagueLabel": "Équipes Nationales",
    "color": "#1C7C3F",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 8000,
    "discountPct": 41,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": true,
    "description": "Maillot domicile réplique Maroc, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-09.jpg",
    "imageSvg": "images/products/maillot-domicile-maroc.svg",
    "imageWide": "images/gallery/gallery-09.jpg",
    "stock": 3,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 74,
    "slug": "maillot-domicile-italie",
    "name": "Maillot Domicile Italie",
    "team": "Italie",
    "kit": "Domicile",
    "league": "equipes-nationales",
    "leagueLabel": "Équipes Nationales",
    "color": "#1C7C3F",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 10500,
    "discountPct": 30,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Italie, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-10.jpg",
    "imageSvg": "images/products/maillot-domicile-italie.svg",
    "imageWide": "images/gallery/gallery-10.jpg",
    "stock": 14,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 75,
    "slug": "maillot-domicile-pays-bas",
    "name": "Maillot Domicile Pays-Bas",
    "team": "Pays-Bas",
    "kit": "Domicile",
    "league": "equipes-nationales",
    "leagueLabel": "Équipes Nationales",
    "color": "#1C7C3F",
    "season": "2026/2027",
    "priceOriginal": 15000,
    "price": 15000,
    "discountPct": 0,
    "isNew": true,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Pays-Bas, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-11.jpg",
    "imageSvg": "images/products/maillot-domicile-pays-bas.svg",
    "imageWide": "images/gallery/gallery-11.jpg",
    "stock": 0,
    "rating": null,
    "reviews": 0
  },
  {
    "id": 76,
    "slug": "maillot-domicile-croatie",
    "name": "Maillot Domicile Croatie",
    "team": "Croatie",
    "kit": "Domicile",
    "league": "equipes-nationales",
    "leagueLabel": "Équipes Nationales",
    "color": "#1C7C3F",
    "season": "2026/2027",
    "priceOriginal": 13500,
    "price": 13500,
    "discountPct": 0,
    "isNew": false,
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "kidsAvailable": false,
    "description": "Maillot domicile réplique Croatie, saison 2026/2027. Tissu respirant, floquage haute qualité résistant au lavage, coupe sport confortable.",
    "image": "images/photos/photo-12.jpg",
    "imageSvg": "images/products/maillot-domicile-croatie.svg",
    "imageWide": "images/gallery/gallery-12.jpg",
    "stock": 1,
    "rating": null,
    "reviews": 0
  }
];

window.LEAGUES = {
  "ligue-1": {
    "label": "Ligue 1",
    "color": "#0055A4",
    "logo": "images/leagues/ligue-1.png",
    "teams": [
      "PSG",
      "Marseille",
      "Lyon",
      "Monaco",
      "Lille",
      "Rennes",
      "Nice",
      "Lens",
      "Strasbourg",
      "Nantes",
      "Toulouse",
      "Montpellier",
      "Brest",
      "Reims",
      "Le Havre",
      "Angers",
      "Auxerre",
      "Metz",
      "Saint-Étienne"
    ]
  },
  "premier-league": {
    "label": "Premier League",
    "color": "#3D195B",
    "logo": "images/leagues/premier-league.png",
    "teams": [
      "Manchester City",
      "Manchester United",
      "Liverpool",
      "Arsenal",
      "Chelsea",
      "Tottenham",
      "Newcastle",
      "Aston Villa",
      "West Ham",
      "Brighton",
      "Everton",
      "Wolves",
      "Crystal Palace",
      "Fulham",
      "Brentford",
      "Nottingham Forest",
      "Bournemouth",
      "Leicester",
      "Southampton"
    ]
  },
  "liga": {
    "label": "Liga",
    "color": "#EE8707",
    "logo": "images/leagues/liga.png",
    "teams": [
      "Real Madrid",
      "Barcelone",
      "Atlético Madrid",
      "Real Sociedad",
      "Séville",
      "Real Betis",
      "Athletic Bilbao",
      "Valence"
    ]
  },
  "serie-a": {
    "label": "Serie A",
    "color": "#008C45",
    "logo": "images/leagues/serie-a.png",
    "teams": [
      "Juventus",
      "Inter Milan",
      "AC Milan",
      "Naples",
      "AS Roma",
      "Fiorentina",
      "Atalanta",
      "Lazio"
    ]
  },
  "bundesliga": {
    "label": "Bundesliga",
    "color": "#D3010C",
    "logo": "images/leagues/bundesliga.png",
    "teams": [
      "Bayern Munich",
      "Borussia Dortmund",
      "RB Leipzig",
      "Bayer Leverkusen",
      "Eintracht Francfort",
      "Borussia Mönchengladbach"
    ]
  },
  "equipes-nationales": {
    "label": "Équipes Nationales",
    "color": "#1C7C3F",
    "logo": "images/leagues/equipes-nationales.png",
    "teams": [
      "Cameroun",
      "France",
      "Brésil",
      "Argentine",
      "Portugal",
      "Espagne",
      "Allemagne",
      "Angleterre",
      "Belgique",
      "Sénégal",
      "Côte d'Ivoire",
      "Nigeria",
      "Maroc",
      "Italie",
      "Pays-Bas",
      "Croatie"
    ]
  }
};

window.GALLERY = [
  {
    "src": "images/gallery/gallery-01.jpg",
    "thumb": "images/photos/photo-01.jpg"
  },
  {
    "src": "images/gallery/gallery-02.jpg",
    "thumb": "images/photos/photo-02.jpg"
  },
  {
    "src": "images/gallery/gallery-03.jpg",
    "thumb": "images/photos/photo-03.jpg"
  },
  {
    "src": "images/gallery/gallery-04.jpg",
    "thumb": "images/photos/photo-04.jpg"
  },
  {
    "src": "images/gallery/gallery-05.jpg",
    "thumb": "images/photos/photo-05.jpg"
  },
  {
    "src": "images/gallery/gallery-06.jpg",
    "thumb": "images/photos/photo-06.jpg"
  },
  {
    "src": "images/gallery/gallery-07.jpg",
    "thumb": "images/photos/photo-07.jpg"
  },
  {
    "src": "images/gallery/gallery-08.jpg",
    "thumb": "images/photos/photo-08.jpg"
  },
  {
    "src": "images/gallery/gallery-09.jpg",
    "thumb": "images/photos/photo-09.jpg"
  },
  {
    "src": "images/gallery/gallery-10.jpg",
    "thumb": "images/photos/photo-10.jpg"
  },
  {
    "src": "images/gallery/gallery-11.jpg",
    "thumb": "images/photos/photo-11.jpg"
  },
  {
    "src": "images/gallery/gallery-12.jpg",
    "thumb": "images/photos/photo-12.jpg"
  },
  {
    "src": "images/gallery/gallery-13.jpg",
    "thumb": "images/photos/photo-13.jpg"
  },
  {
    "src": "images/gallery/gallery-14.jpg",
    "thumb": "images/photos/photo-14.jpg"
  },
  {
    "src": "images/gallery/gallery-15.jpg",
    "thumb": "images/photos/photo-15.jpg"
  },
  {
    "src": "images/gallery/gallery-16.jpg",
    "thumb": "images/photos/photo-16.jpg"
  }
];

window.TESTIMONIALS = [];
